echo "🧪 Testing Chrome Extension..."
echo ""
echo "📋 Pre-flight Checklist:"
echo "✅ Extension files built successfully"
echo "✅ All JavaScript files have valid syntax"
echo "✅ Manifest.json is properly formatted"
echo "✅ Popup.html has proper structure"
echo ""
echo "🚀 Loading Instructions:"
echo "1. Open Chrome browser"
echo "2. Navigate to chrome://extensions/"
echo "3. Enable 'Developer mode' (toggle in top-right)"
echo "4. Click 'Load unpacked'"
echo "5. Select this folder: $(pwd)\dist"
echo ""
echo "🔍 Testing Steps:"
echo "1. Look for 'Resume Tailor' extension in the extensions list"
echo "2. Click the extension icon in the Chrome toolbar"
echo "3. Popup should show 'Resume Tailor' interface (no blank screen)"
echo "4. Navigate to linkedin.com/jobs or indeed.com"
echo "5. Click extension icon again - should detect job posting"
echo ""
echo "🐛 If you see a blank screen:"
echo "- Check Console (F12) for JavaScript errors"
echo "- Verify all files exist in dist/ folder"
echo "- Try reloading the extension"
echo ""
echo "📁 Extension files location: $(pwd)\dist"
Get-ChildItem "dist" | Format-Table Name, Length -AutoSize
